### ISSUE TITLE
Don't work anymore

### ISSUE THREAD

**Issue by tawafimu** [J4A-Industries/LighterFuel-For-Tinder#1]
After last update of firefox it stopped working, about week ago

![obraz](https://github.com/J4A-Industries/LighterFuel-For-Tinder/assets/84072043/8b1c9a40-fee1-4c51-a6f9-6a2a3743aff8)

**Comment by Acorn221** [comment]
Hey there, try out the latest release [here](https://github.com/J4A-Industries/LighterFuel-For-Tinder/releases/tag/v1.4.8), this should be the same version that is currently live on the chrome web store.
It broke as tinder stopped sending the dates of when the images were uploaded, so I've come up with a work-around to show when the accounts were made.
Let me know if you have any issues, the current live version _works_ but is a quite buggy.
